apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zpy-platform-k8s-deploy-action
  description: Github Action to deploy app in k8s
  annotations:
    github.com/project-slug: zapay-pagamentos/zpy-platform-k8s-deploy-action
spec:
  type: library
  lifecycle: production
  owner: darrell
